flickity.group.*:
  type: config_entity
  label: 'Group'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    settings:
      type: mapping
      label: 'Settings'
      mapping:
        images_loaded:
          type: boolean
          label: 'imagesLoaded'
          text: 'Provides support for imagesLoaded plugin.'
        cell_selector:
          type: string
          label: 'Cell selector'
          text: 'Specify selector for cell elements.'
        initial_index:
          type: integer
          label: 'Initial index'
          text: 'Zero-based index of the initial selected cell.'
        accessibility:
          type: boolean
          label: 'Accessibility'
          text: 'Enable keyboard navigation. Users can tab to a Flickity gallery, and pressing left & right keys to change cells.'
        set_gallery_size:
          type: boolean
          label: 'Set gallery size'
          text: 'Sets the height of the gallery to the height of the tallest cell.'
        resize:
          type: boolean
          label: 'Resize'
          text: 'Adjusts sizes and positions when window is resized.'
        cell_align:
          type: string
          label: 'Cell align'
          text: 'Align cells within the gallery element.'
        contain:
          type: boolean
          label: 'Contain'
          text: 'Contains cells to gallery element to prevent excess scroll at beginning or end.'
        percent_position:
          type: boolean
          label: 'Percent position'
          text: 'Sets positioning in percent values, rather than pixel values.'
        right_to_left:
          type: boolean
          label: 'Right to left'
          text: 'Enables right-to-left layout.'
        draggable:
          type: boolean
          label: 'Draggable'
          text: 'Enables dragging and flicking.'
        free_scroll:
          type: boolean
          label: 'Free scroll'
          text: 'Enables content to be freely scrolled and flicked without aligning cells to an end position.'
        lazy_load:
          type: integer
          label: 'Lazy load'
          text: 'Loads cell images when a cell is selected.'
        auto_play:
          type: integer
          label: 'Auto play'
          text: 'Automatically advances to the next cell.'
        wrap_around:
          type: boolean
          label: 'Wrap around'
          text: 'At the end of cells, wrap-around to the other end for infinite scrolling.'
        group_cells:
          type: integer
          label: 'Group Cells'
          text: 'Groups cells together in slides. Flicking, page dots, and previous/next buttons are mapped to group slides, not individual cells.'
        adaptive_height:
          type: boolean
          label: 'Adaptive Height'
          text: 'Changes height of carousel to fit height of selected slide.'
        watch_css:
          type: boolean
          label: 'Watch CSS'
          text: 'You can enable and disable Flickity with CSS.'
        as_nav_for:
          type: string
          label: 'As nav for'
          text: 'Use one Flickity gallery as navigation for another.'
        drag_threshold:
          type: integer
          label: 'Drag Threshold'
          text: 'The number of pixels a mouse or touch has to move before dragging begins.'
        selected_attraction:
          type: float
          label: 'Selected attraction'
          text: 'Attracts the position of the slider to the selected cell. Higher attraction makes the slider move faster.'
        friction:
          type: float
          label: 'Friction'
          text: 'Slows the movement of slider. Higher friction makes the slider feel stickier and less bouncy.'
        free_scroll_friction:
          type: float
          label: 'Free scroll friction'
          text: 'Slows movement of slider when freeScroll: true. Higher friction makes the slider feel stickier.'
        prev_next_buttons:
          type: boolean
          label: 'Previous next buttons'
          text: 'Creates and enables previous & next buttons.'
        page_dots:
          type: boolean
          label: 'Page dots'
          text: 'Creates and enables page dots (pagination).'
